import { parseAbi } from 'viem';

export const gameAbi = parseAbi([
  'function owner() view returns (address)',
  'function nextRunId() view returns (uint32)',
  'function createRun(string seriesAsset, uint64 intervalSec, bytes32 venueId, uint32 targetSurvivors, uint32 maxRounds, uint32 maxPlayers, uint256 entryStake, uint256 minPosition) returns (uint32 runId)',
  'function register(uint32 runId)',
  'function startRun(uint32 runId, bytes32 marketId)',
  'function armForRound(uint32 runId, bytes32 marketId)',
  'function claim(uint32 runId)',
  'function registered(uint32 runId, address player) view returns (bool)',
  'function eliminated(uint32 runId, address player) view returns (bool)',
  'function eliminatedInRound(uint32 runId, address player) view returns (uint32)',
  'function claimant(uint32 runId, address player) view returns (bool)',
  'function claimed(uint32 runId, address player) view returns (bool)',
  'function commentary(uint32 runId, uint32 round) view returns (string)',
  'function getPlayers(uint32 runId) view returns (address[])',
  'function getAlive(uint32 runId) view returns (address[])',
  'function getRun(uint32 runId) view returns ((string seriesAsset,uint64 intervalSec,bytes32 venueId,uint32 targetSurvivors,uint32 maxRounds,uint32 maxPlayers,uint32 roundCount,uint32 survivorCount,uint32 claimantCount,uint32 claimedCount,uint256 entryStake,uint256 minPosition,uint256 prizePool,uint256 unclaimedPrize,bytes32 trackedMarketId,address marketAddress,uint256 yesId,uint256 noId,uint256 subscriptionId,uint8 status))',
  'event RunCreated(uint32 indexed runId, string asset, uint64 intervalSec)',
  'event PlayerRegistered(uint32 indexed runId, address indexed player)',
  'event RoundArmed(uint32 indexed runId, uint32 indexed round, bytes32 indexed marketId)',
  'event PlayerEliminated(uint32 indexed runId, uint32 indexed round, address indexed player)',
  'event RoundSettled(uint32 indexed runId, uint32 indexed round, bytes32 indexed marketId, uint8 winningSide, uint32 eliminatedCount, uint32 survivorsRemaining)',
  'event RoundVoided(uint32 indexed runId, uint32 indexed round, bytes32 indexed marketId)',
  'event RunFinalized(uint32 indexed runId, uint32 claimantCount, uint256 prizePool)',
  'event CommentaryReady(uint32 indexed runId, uint32 indexed round, string text)',
]);

export const erc20Abi = parseAbi([
  'function approve(address spender, uint256 amount) returns (bool)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function balanceOf(address owner) view returns (uint256)',
  'function decimals() view returns (uint8)',
  'function faucet(uint256 amount)',
]);

export const marketCreatedEvent = {
  type: 'event',
  name: 'MarketCreated',
  inputs: [
    { name: 'marketId', type: 'bytes32', indexed: true },
    { name: 'market', type: 'address', indexed: true },
    { name: 'pool', type: 'address', indexed: true },
    { name: 'oracleQuestionId', type: 'uint256', indexed: false },
    { name: 'operatorId', type: 'uint32', indexed: false },
    { name: 'venueId', type: 'bytes32', indexed: false },
    { name: 'creator', type: 'address', indexed: false },
    { name: 'collateral', type: 'address', indexed: false },
    { name: 'yesId', type: 'uint256', indexed: false },
    { name: 'noId', type: 'uint256', indexed: false },
    { name: 'nonce', type: 'uint64', indexed: false },
    { name: 'outcomeSlotCount', type: 'uint8', indexed: false },
    { name: 'marketType', type: 'uint8', indexed: false },
    { name: 'tradingStart', type: 'uint64', indexed: false },
    { name: 'expiry', type: 'uint64', indexed: false },
    { name: 'voidPolicy', type: 'uint8', indexed: false },
    { name: 'asset', type: 'string', indexed: false },
    { name: 'strike', type: 'uint256', indexed: false },
    { name: 'question', type: 'string', indexed: false },
    { name: 'context', type: 'bytes', indexed: false },
  ],
  anonymous: false,
} as const;
